---
title: "Greenhouse data"
output: html_notebook
---

## Greenhouse data for tanks

```{r}
library(data.table)
library(ggplot2)
theme_set(theme_minimal())

greenhouse <- fread("data/greenhouse.csv")
greenhouse[, date := as.Date(date, format = "%m/%d/%y")]
greenhouse[, time := difftime(date, date[1], units = "days")]
greenhouse[, inoculum := "EIT"]
greenhouse[tank %in% 1:3, inoculum := "CIT"]
greenhouse[, tank := factor(tank)]
greenhouse <- greenhouse[order(time, tank)]
indicators <- greenhouse[, .(time, tank, inoculum, 
                             `chlorine (ppm)` = chlorine, 
                             `alkalinity (ppm)` = alkalinity, pH, 
                             `conductivity (uS/cm)`, 
                             `hardness (ppm)` = hardness, 
                             `total fish food (#pellets)` = `total fish food`, 
                             `water added (L)`, 
                             `water temperature (ºC)` = `water temperature`, 
                             `greenhouse humidity (%)` = greenhouse_humidity)]
# Remove impossible humidity values
indicators[`greenhouse humidity (%)` > 100, `greenhouse humidity (%)` := NA]
indicators <- melt(indicators, id.vars=c("time", "tank", "inoculum"), variable.name="measure")
indicators[, value := as.numeric(value)]

sampling_dates <- difftime(as.Date(c("2017-06-28", "2017-07-19", "2017-08-28")),
                           greenhouse$date[1], units = "days")
```

Plot indicators across time

```{r, fig.width=8, fig.height=6}
ggplot(indicators[!is.na(value)], aes(x=time, y=value, color=inoculum, fill = inoculum, group=inoculum)) + 
  geom_point(alpha=0.5) + stat_smooth() + facet_wrap(~ measure, scales = "free_y") +
  labs(x = "time [days]")
ggsave("figures/indicators_time.png", width=8, height=6, dpi=300)
```


As boxplots

```{r, fig.width=6, fig.height=5}
ggplot(indicators, aes(x=tank, y=value, color=inoculum)) + 
  geom_boxplot() + facet_wrap(~ measure, scales="free_y") + 
  guides(color=FALSE)
ggsave("figures/indicators.png", width=6, height=5, dpi = 300)
```

```{r}
nitrogen <- melt(greenhouse[, .(time, tank, inoculum, nitrate, nitrite, ammonia)],
                 id.vars=c("time", "tank", "inoculum"), variable.name="measure")
nitrogen[, value := as.numeric(value)]
```

```{r, fig.width=8, fig.height=4}
nitrogen[, measure := factor(measure, levels=c("ammonia", "nitrite", "nitrate"))]
ggplot(nitrogen, aes(x=time, y=value, color=measure)) + 
  geom_point() + stat_smooth(aes(fill = measure)) + facet_grid(measure ~ tank, scales="free_y") +
  geom_vline(xintercept=sampling_dates, lty="dashed") +
  guides(color = FALSE, fill = FALSE) +
    labs(x = "time [days]", y = "concentration [ppm]")
ggsave("figures/nitrogen_time.png", width = 8, height = 4, dpi = 300)
```

Relationship with plant growth:

We will plot the area under the curve vs the plant measure.

```{r}
library(phyloseq)

trapz <- function(x, y) {
  y[is.na(y)] <- 0
  sum((y[2:length(y)] + y[1:(length(y) - 1)]) * as.numeric(diff(x))) * 0.5
}

aucs <- nitrogen[, .(auc = trapz(time, value), inoculum = inoculum[1]), by=c("measure", "tank")]
plants <- as(sample_data(readRDS("data/taxonomy.rds")), "data.frame") %>% setDT()
plants[, tank := factor(tank)]
plants <- melt(plants[sample_set == "T2" & compartment == "biofilter"], 
               id.vars="tank", measure.vars = c("no_leaves", "root_length", "height", "dead_fish"), 
               variable.name = "plant_measure")

aucs <- aucs[plants, on="tank", allow.cartesian = T]

ggplot(aucs, aes(x=value, y=auc, color=inoculum)) + geom_point() + 
  facet_grid(measure ~ plant_measure, scales="free") +
    stat_smooth(method="lm", aes(group = 1))
ggsave("data/aucs_nitrogen.pdf")
```

And the corresponding statistics:

```{r}
tests <- aucs[, .(
  rsquared = summary(lm(value ~ auc))$r.squared,
  pval = anova(lm(value ~ auc))[1, 5]
  ), by = c("measure", "plant_measure")]
tests[pval<0.1]
```